- docs/team/yusufaine.md
Closes #17 
Checking to see if this gets picked up as v1.1.
> docs: update PPP and AboutUs -- Yusuf

- src/main/java/seedu/address/model/recipe/Recipe.java
> refactor: rename directions variable to steps

- src/main/java/seedu/address/model/recipe/CompletionTime.java
- src/main/java/seedu/address/model/recipe/Recipe.java
> Recipe: add completionTime attribute to recipe class

- README.md
- docs/DeveloperGuide.md
- docs/_config.yml
> chore: update website and product scope of DG

- src/main/java/seedu/address/model/recipe/Step.java
- src/test/java/seedu/address/model/recipe/CompletionTimeTest.java
- src/test/java/seedu/address/model/recipe/NameTest.java
- src/test/java/seedu/address/model/recipe/ServingSizeTest.java
- src/test/java/seedu/address/model/recipe/StepTest.java
modified Step to strip input string and check for isEmpty instead of isBlank for consistency with Name
!! mainly to check if Test increases CodeCoverage score
Remaining files to run tests on for in `model/recipe`:
1. Ingredient,
2. Recipe, and
3. UniqueRecipeList
> test: add test files for model/recipe

- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/parser/AddRecipeCommandParser.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/RecipeBookParser.java
- src/main/java/seedu/address/model/recipe/Recipe.java
> feat: add DELETE command to McKitchen

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/commons/util/StringUtil.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/AddRecipeCommandParser.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/logic/parser/Parser.java
- src/main/java/seedu/address/logic/parser/RecipeBookParser.java
- src/main/java/seedu/address/model/recipe/Recipe.java
- src/main/java/seedu/address/model/recipe/RecipeContainsKeywordPredicate.java
- src/main/java/seedu/address/model/recipe/SearchSet.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
Closes #7.
We will have to test this out when all the features start working
together.
usage:
`find keyword [, comma-seperated keywords]`
> feat!: add FindCommand feature

- src/main/java/seedu/address/commons/util/StringUtil.java
- src/main/java/seedu/address/model/recipe/Recipe.java
- src/main/java/seedu/address/model/recipe/RecipeContainsKeywordPredicate.java
- src/main/java/seedu/address/model/recipe/SearchSet.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
> fix: FindCommand is now case-insensitive

- docs/UserGuide.md
Improve navigability by adding hyperlinks to jump between sections and TOC (which is to be updated).
Closes #69
> docs: update UG with FindCommand usage

- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/parser/RecipeBookParser.java
- src/test/java/seedu/address/logic/commands/ListCommandTest.java
> feat!: implement ListCommand

- src/main/java/seedu/address/logic/commands/ExitCommand.java
- src/main/java/seedu/address/logic/parser/RecipeBookParser.java
- src/test/java/seedu/address/logic/commands/ExitCommandTest.java
Closes #80.
Todo: Update test for ExitCommand
> feat!: implement ExitCommand

- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/RecipeBookSyntax.java
- src/main/java/seedu/address/logic/parser/ViewCommandParser.java
Closes #83.
This was a quick solution so it might not be *optimal*.
This can be used to for other index-based operations as well.
> feat!: access (view/delete) recipe by index

- src/test/java/seedu/address/model/recipe/CompletionTimeTest.java
- src/test/java/seedu/address/model/recipe/NameTest.java
- src/test/java/seedu/address/model/recipe/ServingSizeTest.java
- src/test/java/seedu/address/model/recipe/StepTest.java
- src/test/java/seedu/address/model/tag/TagTest.java
100% Code Coverage for:
- CompletionTime (Closes #90)
- Name (Closes #91)
- ServingSize (Closes #92)
- Step (Closes #95)
- Tag (Closes #96)
> test: improve code coverage for the files below

- src/main/java/seedu/address/model/recipe/SearchSet.java
- src/test/java/seedu/address/model/recipe/SearchSetTest.java
100% code coverage for `SearchSet`
Closes #98
> test: improve code coverage for SearchSet

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/RecipeBookParserUtil.java
Closes #88.
Please test and ensure all commands work as expected thanks boys (and girl) 👍 
Also temporarily placed one of the utils function to compare recipe names in the ParserUtil class
> Refactor: refactor and standardize Command classes, fix Delete and View commands

- src/test/java/seedu/address/logic/parser/RecipeBookSyntaxTest.java
> test: improve CC for RecipeBookSyntax

- src/test/java/seedu/address/model/recipe/CompletionTimeTest.java
- src/test/java/seedu/address/model/recipe/NameTest.java
- src/test/java/seedu/address/model/recipe/SearchSetTest.java
- src/test/java/seedu/address/model/recipe/ServingSizeTest.java
- src/test/java/seedu/address/model/recipe/StepTest.java
- src/test/java/seedu/address/model/tag/TagTest.java
Changes were made with respect to the discussion [here](https://github.com/AY2122S2-CS2103T-T17-2/tp/pull/105#issuecomment-1072001031).
> refactor: update test method names 

- src/main/java/seedu/address/logic/parser/Prefix.java
- src/test/java/seedu/address/logic/parser/PrefixTest.java
Closes #108
Slight refactor of Prefix to match how we've formatted the layout of our code for the other classes.
> test: improve code coverage for Prefix

- docs/DeveloperGuide.md
I've only edited a few lines to fulfil this week's requirement of updating at least 5 LOC for DG.
> docs: update DG for week 10 criteria

- docs/UserGuide.md
Update command summary of user guide section with format of add and edit commands.
> Docs: update command summary section with add and edit commands

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/ExitCommand.java
- src/main/java/seedu/address/logic/commands/HelpCommand.java
- src/main/java/seedu/address/logic/parser/RecipeBookParser.java
- src/main/java/seedu/address/ui/HelpWindow.java
- src/test/java/seedu/address/commons/core/index/IndexTest.java
- src/test/java/seedu/address/logic/commands/HelpCommandTest.java
This would address the users who would like to see a summary of commands that they would like to refer to.
Closes #121 and testing for HelpCommand
> feat!: implement HelpCommand

- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/ResetCommand.java
- src/main/java/seedu/address/logic/parser/RecipeBookParser.java
- src/main/java/seedu/address/model/util/RecipeList.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/test/java/seedu/address/logic/commands/ClearCommandTest.java
- src/test/java/seedu/address/logic/commands/ResetCommandTest.java
Chore: Populate sample recipes
> Chore: Populate sample recipes

- docs/UserGuide.md
We also updated the Command Summary and FAQ to improve its clarity.
> docs: reformat TOC and add Help feature

- src/main/java/seedu/address/ui/RecipeCard.java
- src/main/java/seedu/address/ui/ResultDisplay.java
- src/main/resources/view/CremeTheme.css
- src/main/resources/view/RecipeListCard.fxml
Changes:
* Fixes recipe index not showing in list view for recipes with
long names.
* Adds dynamic text wrapping for ingredients and steps in result
display.
* Removes unnecessary GridPane from RecipeListCard.fxml
> fix: apply fixes and updates to UI

- docs/team/blaketingyu.md
> docs: update PPP

- docs/team/blaketingyu.md
> Add blake info
